// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GQugQYZ7LN1w_et1zS8UpJkZ1UXsVNo',
    appId: '1:42745284043:web:92dc7d406590cbedb1224e',
    messagingSenderId: '42745284043',
    projectId: 'virtualhomerent',
    authDomain: 'virtualhomerent.firebaseapp.com',
    storageBucket: 'virtualhomerent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WoyT_OluFsSh5ZGT12SF8ifjRvR3O84',
    appId: '1:42745284043:android:20b3c51e909a1967b1224e',
    messagingSenderId: '42745284043',
    projectId: 'virtualhomerent',
    storageBucket: 'virtualhomerent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIAYZuAOz9QSu7mg0L2f88ni4JTDYUCE',
    appId: '1:42745284043:ios:b5528ebd82d2331bb1224e',
    messagingSenderId: '42745284043',
    projectId: 'virtualhomerent',
    storageBucket: 'virtualhomerent.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIAYZuAOz9QSu7mg0L2f88ni4JTDYUCE',
    appId: '1:42745284043:ios:5c86bf270fad85d5b1224e',
    messagingSenderId: '42745284043',
    projectId: 'virtualhomerent',
    storageBucket: 'virtualhomerent.appspot.com',
    iosBundleId: 'com.example.hackathon.RunnerTests',
  );
}
